import { buildApp } from './app.js'
import { config } from './config.js'
import { enableWal, prisma } from './db/client.js'
import { pruneGeneratedFixtureRows, seedFixtures } from './fixtures/seed.js'
import { logger } from './logger.js'

async function main(): Promise<void> {
  await enableWal(prisma)

  // D3 — idempotent seed on every boot, so a wiped disk self-heals to a
  // known-good fixture state. Δ1 is explicit that this restores the FIXTURE
  // WORLD and not job state.
  if (config.seedOnBoot) {
    await seedFixtures(prisma)
    logger.info('fixtures seeded (idempotent)')
  }
  // APPLY-L — seeding restores the fixture world; only this removes what
  // previous transfers added to it. Off under a production-like NODE_ENV.
  if (config.pruneGeneratedOnBoot) {
    const pruned = await pruneGeneratedFixtureRows(prisma)
    logger.info('pruned rows generated by previous transfers', { ...pruned })
  }

  const { app, reconciler } = buildApp({ prisma })

  // D12 — reconcile at boot AND on an interval. Boot alone leaves a job wedged
  // by a rejected promise chain polling forever while the process is alive.
  const bootResult = await reconciler.reconcileStaleJobs()
  if (bootResult.jobsReconciled > 0) {
    logger.info('boot reconciliation resolved interrupted jobs', { ...bootResult })
  }
  const stopReconciler = reconciler.start(config.reconcilerIntervalMs)

  const server = app.listen(config.port, () => {
    logger.info('classroom-copier api listening', {
      port: config.port,
      providerMode: config.googleProviderMode,
      monetizationEnabled: config.featureMonetizationEnabled,
    })
  })

  const shutdown = (signal: string) => {
    logger.info('shutting down', { signal })
    stopReconciler()
    server.close(() => {
      void prisma.$disconnect().finally(() => process.exit(0))
    })
  }
  process.on('SIGTERM', () => shutdown('SIGTERM'))
  process.on('SIGINT', () => shutdown('SIGINT'))
}

main().catch((error: unknown) => {
  logger.error('failed to start', {
    error: error instanceof Error ? error.message : String(error),
  })
  process.exit(1)
})
